# Generated by Django 5.1.3 on 2025-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='Ford', max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('carroceria', models.CharField(max_length=50, verbose_name='Carrocería')),
                ('motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('particular', 'particular'), ('transporte', 'transporte'), ('carga', 'carga')], default='particular', max_length=20, verbose_name='Categoría')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
